import express from 'express'
import crypto from 'crypto'

const app = express()

app.get('/', (req, res) => {
    // gets the ip adress
    const device_ip = req.ip
    // gets the 16 random bytes
    let iv = crypto.randomBytes(16)
    // random key. Generated by: https://www.avast.com/random-password-generator
    let key = 'UZDIvJ1dQtVZRvKzgqMMfDlc7uM3tkA2'
    // encryption of the ip
    let cipher = crypto.createCipheriv('aes-256-cbc', key, iv)
    let encrypted = cipher.update(device_ip, 'utf-8', 'hex')
    encrypted += cipher.final('hex')
    // decryption of the ip
    let decipher = crypto.createDecipheriv('aes-256-cbc', key, iv)
    let decrypted = decipher.update(encrypted, 'hex', 'utf-8')
    decrypted += decipher.final('utf-8')
    // server response
    return res.json({ device_ip, encrypted, decrypted })
})

app.listen(8320, () => {
    console.log(`🍎 Up and runing on http://localhost:8320/ 🍏`)
})
